easy_admin:
  site_name: "Jungles dashboard"

  list:
    max_results: 50

  show:
    max_results: 50

  formats:
    date: "d/m/Y"
    time: "H:i"
    datetime: "d/m/Y H:i:s"

  user:
    display_name: true
    display_avatar: false
    name_property_path: "username"
