# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
  adapters:
    default_adapter:
      local:
        directory: "%kernel.project_dir%/public"
    privacy_adapter:
      awss3v3:
        client: app.s3_client
        bucket: "jungles-s3"
        prefix: "%env(S3_PREFIX)%"
  filesystems:
    default_filesystem:
      adapter: default_adapter
      alias: League\Flysystem\Filesystem
    s3_privacy_fs:
      adapter: privacy_adapter
      mount: s3_privacy_fs
      alias: s3_privacy_filesystem
      visibility: private
